getanswer/urls.py
# for the image
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

from django.urls import path, include
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "GetAnswer Admin"
admin.site.site_title = "GetAnswer Admin Panel"
admin.site.index_title = "Welcome to GetAnswer Admin Panel"

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('QandA/', include('question_answer.urls')),
    path('all_games/', include('games.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('essay_and_bio/', include('essay_and_bio.urls', namespace='essay_and_bio')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('blog', include('blog.urls')),
]
handler404 = "home.views.error_404"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

app_name = 'home'
urlpatterns = [
    path('', views.home, name="home"),
    path('about', views.about, name='about'),
    path('dictionary', views.dictionary, name='dictionary'),
    path('login',views.handeLogin, name='handeLogin' ),
     
    # path('search', views.search, name='search'),
    path('search_qanda', views.search_qanda, name='search_qanda'),
    path('search_essays', views.search_essays, name='search_essays'),
    path('all_class/<str:class_name>', views.all_class, name='all_class'),
    
    path('aboutus', views.aboutus, name="aboutus"),
    path('contactus', views.contactus, name="contactus"),
    path('policy_privacy', views.policy_privacy, name="policy_privacy"),
    path('termsandcontions', views.termsandcontions, name="termsandcontions"),

     
]

question_answer/urls.py
from django.contrib import admin
from django.urls import path, include
from question_answer import views
from .views import question_ansewr_UpdateView
app_name = "question_answer"

urlpatterns = [
    # answer questions page urls
    path('', views.all_questions_answers, name='all_questions_answers'),
    path('getanswer/<str:slug>',
         views.read_all_questions_answers, name='read_all_questions_answers'),

   # upload urls
    path('upload_qanda_on_getanswr_9813587726', views.upload_qanda_on_getanswr_9813587726,
         name='upload_qanda_on_getanswr_9813587726'),

    # Management urls
    path('dashboard_ans', views.dashboard_ans, name='dashboard_ans'),
    path('<str:slug>/update_ans', views.question_ansewr_UpdateView.as_view(), name='update_ans'),
    path('<str:slug>/delete_ans', views.delete_ans, name='delete_ans'),

]

question_answer/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
# Create your views here.

# which class they are reading.


class which_author(models.Model):
    author = models.CharField(max_length=255)
    bio = models.TextField(max_length=5000)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.author


class which_type(models.Model):
    types = models.CharField(max_length=255)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.types


class which_grade (models.Model):
    grade = models.CharField(max_length=255)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.grade


class which_language(models.Model):
    language = models.CharField(max_length=255)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.language


class which_subject(models.Model):
    subject = models.CharField(max_length=255)
    image = models.ImageField(default='bg.png', upload_to='avatars/')
    bio = models.CharField(max_length=255)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.subject



class which_subject_category(models.Model):
    subject_category = models.CharField(max_length=255)
    icon = models.CharField(max_length=255)
    bio = models.CharField(max_length=255)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.subject_category


# answer question, quiz,different between,quiz, Full forms, different between
class answer_question(models.Model):
    sno = models.AutoField(primary_key=True)
    user= models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='answer_question')
    author = models.CharField(max_length=255)
    question = models.CharField(max_length=255)
    content = models.TextField()
    tags = models.TextField(max_length=5555)
    types = models.CharField(max_length=255)
    grade = models.CharField(max_length=255)
    language = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
   
    subject_category = models.CharField(max_length=255)
    
    slug = AutoSlugField(populate_from='question',
                         unique=True, null=False, default=False)
    
    stars = models.IntegerField(default=1)
    views = models.IntegerField(default=0)
    timeStamp = models.DateTimeField(auto_now=True)
    def __str__(self):
        return " Question: " + self.question + " by " + self.author + " " + self.grade



question_answer/forms.py
from django import forms
from .models import answer_question

class answer_questionForm (forms.ModelForm):
    answer = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    tags = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))
    class Meta:
        model= answer_question
        fields =  ('author','question','content','tags','types','grade','language','subject_category')

question_answer/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth import authenticate,  login, logout
from essay_and_bio.models import essay_and_bio
from .models import *
from django.db import IntegrityError
from django.core.paginator import Paginator
import datetime
from games.models import all_game_info
from django.urls import reverse_lazy
from profiles.models import Profile
from .forms import answer_questionForm
from django.views.generic import UpdateView, DeleteView
year = datetime.datetime.now().year
# questions answer section



def all_questions_answers(request):
    try:
            suggestios_of_answer_question = answer_question.objects.order_by("-views") 
            Clouds_tags =which_subject.objects.all() 
            read_essays =essay_and_bio.objects.all()[:6]  
            profile = Profile.objects.get(user=request.user)                    
            b_allanswer_question = answer_question.objects.all()
            b_all_class = which_grade.objects.all()
            b_all_subjects = which_subject.objects.all()
            b_all_sub_subjects = which_subject_category.objects.all()
            qanda = answer_question.objects.all()
            paginator = Paginator(b_allanswer_question, 40)
            page_number = request.GET.get('page')
            queston_list = paginator.get_page(page_number)
            new_question = answer_question.objects.order_by('-timeStamp')[0:40]
            top_essays = essay_and_bio.objects.order_by('-timeStamp')[0:8]
            top_games = all_game_info.objects.order_by('-timeStamp')[0:4]

            param = {"suggestios_of_answer_question":suggestios_of_answer_question,"Clouds_tags":Clouds_tags,"read_essays":read_essays,                'profile':profile,'qanda': qanda, "b_allanswer_question": b_allanswer_question,
                    "b_all_class": b_all_class, "b_all_sub_subjects": b_all_sub_subjects, "b_all_subjects": b_all_subjects, "queston_list": queston_list, "new_question": new_question, "top_essays": top_essays, "top_games": top_games ,"year": year }        
            return render(request, 'question_answer/all_questions_answers.html', param)
    except Exception as e:
        return render(request, 'home/page_not_found.html')


def read_all_questions_answers(request, slug):
    try:                
            Clouds_tags =which_subject.objects.all() 
            read_essays =essay_and_bio.objects.all()[:6]  
            profile = Profile.objects.get(user=request.user)
            quizs = answer_question.objects.filter(slug=slug).first()
            quizs.views = quizs.views + 1
            quizs.save()
            b_allanswer_question = answer_question.objects.all()
            b_all_class = which_grade.objects.all()
            b_all_subjects = which_subject.objects.all()
            b_all_sub_subjects = which_subject_category.objects.all()

            new_question = answer_question.objects.order_by('-timeStamp')[0:25]
            top_essays = essay_and_bio.objects.order_by('-timeStamp')[0:8]
            top_games = all_game_info.objects.order_by('-timeStamp')[0:4]

            params = {"profile":profile,'quizs': quizs, "b_all_sub_subjects": b_all_sub_subjects, "b_allanswer_question": b_allanswer_question, "b_all_class": b_all_class, "b_all_subjects": b_all_subjects,
            "new_question": new_question, "top_essays": top_essays, "top_games": top_games ,"year": year }
        
    
            params = {"Clouds_tags":Clouds_tags,"read_essays":read_essays,'quizs': quizs, "b_all_sub_subjects": b_all_sub_subjects, "b_allanswer_question": b_allanswer_question, "b_all_class": b_all_class, "b_all_subjects": b_all_subjects,
            "new_question": new_question, "top_essays": top_essays, "top_games": top_games ,"year": year }

            return render(request, 'question_answer/readqanda.html', params)
    except Exception as e:
        return render(request, 'home/page_not_found.html')


# upoad section
# Answer Questions, Different Between, Quiz, Technical term, Full Forms
@login_required
def upload_qanda_on_getanswr_9813587726(request):
    all_authors = which_author.objects.all()
    all_sujects = which_subject.objects.all()
    all_sub_subjects = which_subject_category.objects.all()
    all_category = which_type.objects.all()
    all_class = which_grade.objects.all()
    all_language = which_language.objects.all()
    # try:
    if request.method == "POST":
        # Get the post parameters
        user = Profile.objects.get(user=request.user)
        author = request.POST['author']
        question = request.POST['question']
        content = request.POST['content']
        tags = request.POST['tags']
        types = request.POST['types']
        grade = request.POST['grade']
        language = request.POST['language']
        subject = request.POST['subject']
        subject_category = request.POST['subject_category']
        qanda_model = answer_question(user=user,language=language, author=author, question=question, content=content, tags=tags,
          types=types, grade=grade, subject=subject, subject_category=subject_category)
        qanda_model.save()
        uploaded_question =answer_question.objects.order_by('-timeStamp')[0:1]
        print(uploaded_question)
        messages.success(
            request, ("Successfully uploaded!",uploaded_question))

    params = {"all_category": all_category, "all_language": all_language, "all_authors": all_authors, "all_sujects": all_sujects,
                  "all_sub_subjects": all_sub_subjects, "all_class": all_class ,"year": year}

    return render(request, 'question_answer/upload_qanda_on_getanswr.html', params)
    # except Exception as e:
    #     return render(request, 'home/page_not_found.html')


# Management section 
@login_required
def dashboard_ans(request):
    all_ans = answer_question.objects.all()
    profile = Profile.objects.get(user=request.user)
    param={"all_ans":all_ans,"profile":profile ,"year": year}
    return render(request, "question_answer/dashboard_ans.html",param)

class question_ansewr_UpdateView(LoginRequiredMixin, UpdateView ):
    form_class = answer_questionForm
    model = answer_question
    template_name = 'question_answer/update_ans.html'
    success_url = reverse_lazy('question_answer:dashboard_ans')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.user == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You need to be the author of the post in order to update it")
            return super().form_invalid(form)
   

@login_required
def delete_ans(request,slug):
    all_ans =answer_question.objects.get(slug=slug)  
    all_ans.delete()
    return redirect('question_answer:dashboard_ans')


templates/question_answer/dashboard_ans.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Answers {% endblock title %}

<!-- {% block homeactive %} active {% endblock homeactive %} -->
{% block body %}
<div class=" text-center">
              <h3>Answer question, Quiz,Different Between,quiz, Full forms,etc.</h3>
              <div class="row">
                            <div class="col-12 text-center m-3"><a href="/QandA/upload_qanda_on_getanswr_9813587726">
                                                        <button class="btn-sm bg-success">Add More..</button>
                                          </a>
                            </div>
              </div>
              <table class="table table-bordered table-responsive ">

                            <thead class="bg-dark text-light">


                                          <tr>
                                                        <th scope="col">#</th>
                                                        <th scope="col">Qun</th>
                                                        <th scope="col">Ans</th>
                                                        <th scope="col">Author</th>
                                                        <th scope="col">types</th>
                                                        <th scope="col">language</th>
                                                        <th scope="col">subject</th>
                                                        <th scope="col">views</th>
                                                        <th scope="col">class</th>
                                                        <th scope="col">Handle</th>
                                          </tr>
                            </thead>


                            {% for i in all_ans %}
                            {% ifequal request.user i.user.user %}
                            <tbody>
                                          <tr>
                                                        <th scope="row">{{ forloop.counter }}</th>
                                                        <td>{{i.question}}</td>
                                                        <td>
                                                                      <div class="row">
                                                                                    <a href="/QandA/getanswer/{{i.slug}}">
                                                                                                  <p>{{i.content|safe|truncatechars:200}}</p>
                                                                                    </a>
                                                                      </div>
                                                        </td>
                                                        <td>{{i.author}}</td>
                                                        <td>{{i.types}}</td>
                                                        <td>{{i.language}}</td>
                                                        <td>{{i.subject}}</td>
                                                        <td>{{i.views}}</td>
                                                        <td>{{i.grade}}</td>
                                                        <td>
                                                                      <a href="{{i.slug}}/update_ans"><button type="button" class="btn btn-sm btn-outline-primary">Edit</button></a>

                                                                      <a href="{{i.slug}}/delete_ans"> <button type="button" class="btn btn-sm btn-outline-secondary">Delete</button>
                                                                      </a>
                                                        </td>
                                          </tr>
                                          {% endifequal %}



                                          {% endfor %}

                            </tbody>
              </table>
</div>
{% endblock body %}

templates/question_answer/update_ans.html
{% extends 'base.html' %}
{% block title %}
Update question answers, quiz, different between etc.
{% endblock title %}

{% block body %}
<div class="container">
              <div class='ui segment'>
                            <h3>Update post</h3>
                            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                                          {% csrf_token %}
                                          {{form}}
                                          <button type='submit' style="width:95%; margin-top:10px;"
                                                        class="btn btn-sm bg-success">Update</button>
                            </form>

              </div>
              <style>
                            input {
                                          width: 92%;
                                          margin-top: 10px;
                            }

                            textarea {
                                          width: 95%;
                                          margin-top: 10px;
                            }
              </style>
</div>
<script>
              alert("are you sure you want to update the inforation? ")



</script>
{% endblock body%}

templates/question_answer/upload_qanda_on_getanswr.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description"
            content="Toppr makes learning effective for you. Prepare for JEE Main, NEET, JEE Advanced, CBSE and other school exams. Start your free trial today!" />
      <meta property="og:description"
            content="Toppr makes learning effective for you. Prepare for JEE Main, NEET, JEE Advanced, CBSE and other school exams. Start your free trial today!" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
      <link rel=" stylesheet" href="{% static 'css/slick.css'%}">
      <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css">
      <link rel="stylesheet" href="{% static 'css/style.css'%}">

      <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
      <link rel="stylesheet" href="/resources/demos/style.css">
      <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
      <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
      <link rel="icon" href="{% static 'logo.ico ' %}" type="image/x-icon" />
      <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
      <script>
            tinymce.init({
                  selector: '#mytextarea',
                  plugins: [
                        'advlist autolink link image lists charmap print preview hr anchor pagebreak',
                        'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                        'table emoticons template paste help'
                  ],
                  toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
                        'bullist numlist outdent indent | link image | print preview media fullpage | ' +
                        'forecolor backcolor emoticons | help',
                  menu: {
                        favs: { title: 'My Favorites', items: 'code visualaid | searchreplace | emoticons' }
                  },
                  menubar: 'favs file edit view insert format tools table help',
                  content_css: 'css/content.css'
            });
      </script>
</head>

<body>
      <style>
            body {
                  background-color: rgba(172, 181, 182, 0.172) !important;
            }

      </style>
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>Message : </strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-small="Close"></button>
      </div>
      {% endfor %}

      <div class="container ">
            <div class="row">
                  <div class="col-4 text-center my-3">
                        <a href="/QandA/upload_qanda_on_getanswr_9813587726">
                              <button class="btn-sm bg-success">Add More Ans..</button>
                        </a>
                  </div>
                  <div class="col-4">
                        <h5 class="text-center">Upload Answer Question on Answr.com </h5>
                  </div>
                  <div class="col-4 text-center my-3"><a
                              href="/essay_and_bio/upload/upload_essay_and_bio_on_getanswr_9813587726">
                              <button class="btn-sm bg-success">Add
                                    More Essays..</button>
                        </a>
                  </div>
            </div>
            
            <form action="/QandA/upload_qanda_on_getanswr_9813587726" enctype="multipart/form-data" method='post'>

                  <div class="form-group p-2 border-bottom">
                        <small class="text-muted"> " If your are writing your on content than write your name else white the name of the contnet author."</small>

                        <small for="author">Author</small>
                        <input type="text" class="form-control" id="author" name="author"
                              placeholder="Write your author  " required>
                  </div>

                  <div class="form-group p-2 border-bottom">
                        <small class="text-muted"> " Wrtie down your Question in which you are willing to give the answer."</small>

                        <small for="id_question">Question:</small>
                        <input type="text" class="form-control" id="id_question" name="question"
                              placeholder="Write your question  " required>
                  </div>

                  <div class="form-group border-bottom">
                        <small class="text-muted"> "Give your best answers to attract more user in your page. "</small>

                        <small for="mytextarea">Answer</small>
                        <textarea type="text" class="form-control" id="mytextarea" name="content"
                              placeholder="Write the answer " required>
                        </textarea>
                  </div>


                  <div class="form-group p-2 border-bottom">
                        <small for="id_class_name">Select Grade:</small>
                        <select name="grade" id="id_class_name" style="height: 39px;width: 81.1%;">
                              {% for i in all_class %}
                              <option value="{{i.grade}}" style="text-transform: capitalize; color:black;">{{i.grade}}
                              </option>
                              {% endfor %}
                        </select>
                  </div>
                  <!-- =which_category.objects.all() -->
                  <div class="form-group p-2 border-bottom">
                        <small class="text-muted"> " Choose your subject type like QandA, Essays, Biography, Quiz, Anime, etc. "</small>
                        <small for="id_which_category">Select Type:</small>
                        <select name="types" id="id_which_category" style="height: 39px;width: 81.1%;">
                              {% for i in all_category %}
                              <option value="{{i.types}}" style="text-transform: capitalize; color:black;">{{i.types}}
                              </option>
                              {% endfor %}
                        </select>
                  </div>
                  <div class="form-group p-2 border-bottom">
                        <small class="text-muted"> " Choose your subject name like Science, Social, Math, Computer, HPE, English, etc."</small>
                        <small for="id_subject_name">Select Subject Name :</small>
                        <select name="subject" id="id_subject_name" style="height: 39px;width: 81.1%;">
                              {% for i in all_sujects %}
                              <option value="{{i.subject}}" style="text-transform: capitalize; color:black;">
                                    {{i.subject}}</option>
                              {% endfor %}
                        </select>
                  </div>
                  <div class="form-group p-2 border-bottom">
                        <small class="text-muted"> " Choose your subject category like Physic, chemistry, environment, sport, etc"</small>
                        <small for="id_subject_category">Select Subject Category </small>
                        <select name="subject_category" id="id_subject_category" style="height: 39px;width: 81.1%;">
                              {% for i in all_sub_subjects %}
                              <option value="{{i.subject_category}}" style="text-transform: capitalize; color:black;">
                                    {{i.subject_category}}</option>
                              {% endfor %}
                        </select>
                  </div>
                  <div class="form-group my-2 border-bottom py-2">
                        <small for="id_language_name">Select Language </small>
                        <select name="language" id="id_language_name" style="height: 39px;width: 81.1%;">
                              {% for i in all_language %}
                              <option value="{{i.language}}" style="text-transform: capitalize; color:black;">
                                    {{i.language}}</option>
                              {% endfor %}
                        </select>
                  </div>

                  <div class="form-group p-2 border-bottom">
                        <small class="text-muted"> "Write down your tage for the alternative search result of your conetent/document. Warning! every tage should be separated with "," in the ending tage."</small>                       <small for="tags">Tags </small>
                        <textarea type="text" class="form-control" id="tags" name="tags" placeholder="Write the tags"
                              required>
                        </textarea>
                  </div>



                  {% csrf_token %}
                  <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" required>
                        <small class="form-check-small" for="flexCheckDefault">
                              Checkbox
                        </small>
                  </div>
                  <div class="d-grid gap-1 mb-4">
                        <button type="submit" class="btn btn-primary p-2  ">Submit</button>
                  </div>
            </form>

      </div>
      <!-- these is for these page not for the djnago admin  -->


</body>

</html>